"""Copy the generated figures into the manuscript folder.

    python src/figures/sync_figures.py --check
    python src/figures/sync_figures.py --apply

The manuscript keeps its own copy of every graphic so that the folder can be
zipped and sent to the journal on its own. That copy silently goes stale
every time a figure script is re-run, and a stale copy is invisible in the
compiled PDF -- it still shows a figure, just the wrong one. That is how a
whole round of font fixes once got made and never reached the page.

Only the graphics the manuscript actually asks for are copied, so the working
figures that never made it into the paper stay out of the submission folder.
A missing file is reported as an error rather than a copy, because that means
the .tex is asking for something no script produces.
"""

import argparse
from pathlib import Path
import re
import shutil

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "results" / "figures"
DST = ROOT / "manuscript" / "figures"
TEX = ROOT / "manuscript" / "manuscript_revised.tex"

# Author photographs and the reused location map are not generated by any
# script, so they live in the manuscript folder and have no source here.
NO_SOURCE_OK = {"author1.png", "author2.png", "fig_study_area_published.jpg"}

GRAPHIC_RE = re.compile(r"\\includegraphics\s*(?:\[[^\]]*\])?\{([^}]+)\}")


def wanted():
    return sorted({Path(m).name for m in GRAPHIC_RE.findall(TEX.read_text())})


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--apply", action="store_true",
                    help="copy the files (default is a dry run)")
    args = ap.parse_args()

    stale, missing, ok = [], [], 0
    for name in wanted():
        src, dst = SRC / name, DST / name
        if not src.exists():
            if name not in NO_SOURCE_OK:
                missing.append(name)
            continue
        if dst.exists() and dst.stat().st_mtime >= src.stat().st_mtime:
            ok += 1
            continue
        stale.append(name)
        if args.apply:
            shutil.copy2(src, dst)

    for name in stale:
        print(f"  {'copied ' if args.apply else 'stale  '} {name}")
    for name in missing:
        print(f"  MISSING  {name}  (no script produces it)")

    print(f"\n{ok} up to date, {len(stale)} "
          + ("copied" if args.apply else "stale") + f", {len(missing)} missing")
    if missing or (stale and not args.apply):
        raise SystemExit(1)


if __name__ == "__main__":
    main()
